use_frameworks!

target 'TestPrivateCodeRepo_Example' do
  pod 'TestPrivateCodeRepo', :path => '../'

  target 'TestPrivateCodeRepo_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
